# Generated by Django 5.1.1 on 2024-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votetotal',
            name='vote',
        ),
        migrations.AddField(
            model_name='candidates',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
